services:
  postgres:
    image: postgres:15-alpine
    container_name: t_pg
    environment:
      POSTGRES_DB: tdb
      POSTGRES_USER: tu
      POSTGRES_PASSWORD: tp

    ports:
      - "5433:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tu -d tdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
